name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [pull_request]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: "1. Checkout"
        uses: actions/checkout@v4
      - name: "2. Setup node"
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: "3. Install"
        run: npm run ci
      - name: "4. Build"
        run: npm run build
      - name: "5. Test"
        run: npm run test
#        code 복사(action), node.js, build, test
